FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt /app
COPY app.py /app
COPY model.pkl /app
COPY feature_engineer.py /app

RUN pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "app:app", "--host","0.0.0.0","--port","8000"]